"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import StaffWorkspaceShell from "../workspace-shell";

type AccountType="cash"|"bank"|"provider"|"other";
type Account={id:number;code:string;name:string;accountType:AccountType;currency:string;active:number;isDefault:number;createdAt:string;updatedAt:string};
type Staff={email:string;displayName:string;role:string};
type Payload={accounts:Account[];staff:Staff;canEdit:boolean;error?:string};
type Form={id:number|null;code:string;name:string;accountType:AccountType;currency:string;active:boolean;isDefault:boolean};
const EMPTY:Form={id:null,code:"",name:"",accountType:"cash",currency:"UAH",active:true,isDefault:false};
const TYPE_UK:Record<AccountType,string>={cash:"Каса",bank:"Банківський рахунок",provider:"Платіжний провайдер",other:"Інший"};

export default function CashAccountsPage(){
  const [data,setData]=useState<Payload|null>(null);const [form,setForm]=useState<Form>(EMPTY);const [query,setQuery]=useState("");const [type,setType]=useState<"all"|AccountType>("all");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const response=await fetch("/api/staff/cash-accounts",{cache:"no-store"});const payload=await response.json().catch(()=>({})) as Payload;if(!response.ok)throw new Error(payload.error||"Не вдалося завантажити каси і рахунки");setData(payload);setError("");},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load().catch(e=>setError(e instanceof Error?e.message:"Помилка")),0);return()=>window.clearTimeout(timer);},[load]);
  const rows=useMemo(()=>{const q=query.trim().toLowerCase();return(data?.accounts||[]).filter(row=>(type==="all"||row.accountType===type)&&(!q||`${row.name} ${row.code} ${row.currency}`.toLowerCase().includes(q)));},[data,query,type]);
  function edit(row:Account){setForm({id:row.id,code:row.code,name:row.name,accountType:row.accountType,currency:row.currency,active:!!row.active,isDefault:!!row.isDefault});setNotice("");}
  function reset(){setForm(EMPTY);setNotice("");}
  async function save(event:React.FormEvent){event.preventDefault();if(!data?.canEdit)return;setBusy(true);setNotice("");try{const response=await fetch("/api/staff/cash-accounts",{method:form.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const payload=await response.json().catch(()=>({})) as {error?:string;account?:Account};if(!response.ok){setNotice(`⚠ ${payload.error||"Не вдалося зберегти"}`);return;}setNotice(`✓ ${form.id?"Рахунок оновлено":"Рахунок створено"}`);await load();if(payload.account)edit(payload.account);}finally{setBusy(false);}}
  const classificationLocked=!!form.id;
  return <StaffWorkspaceShell active="cash_accounts" title="Каси і рахунки" description="BAS-довідник місць зберігання грошей. Оплата і повернення проводяться по конкретній касі або банківському рахунку." staffName={data?.staff.displayName||data?.staff.email} staffRole={data?.staff.role}>
    {error&&<p className="financeError">{error}</p>}{!data&&!error&&<p className="financeLoading">Завантаження…</p>}
    {data&&<div className="inventoryDocumentsLayout"><section className="financeJournal"><header className="financeToolbar"><div className="financeTabs"><button type="button" onClick={()=>window.location.assign("/staff/finance")}>← Фінанси</button></div><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Пошук: назва, код, валюта…"/><select value={type} onChange={e=>setType(e.target.value as "all"|AccountType)}><option value="all">Усі типи</option>{Object.entries(TYPE_UK).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button type="button" onClick={()=>void load()}>Оновити</button></header><div className="financeTableWrap"><table className="financeTable"><thead><tr><th>Каса / рахунок</th><th>Тип</th><th>Код</th><th>Валюта</th><th>Основний</th><th>Стан</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.name}</b><small>ID {row.id}</small></td><td>{TYPE_UK[row.accountType]}</td><td>{row.code||"—"}</td><td>{row.currency}</td><td>{row.isDefault?<b>Так</b>:"—"}</td><td><span className={`financeState ${row.active?"state-posted":"state-cancelled"}`}>{row.active?"Активний":"Неактивний"}</span></td><td><button type="button" onClick={()=>edit(row)}>Відкрити</button></td></tr>)}{rows.length===0&&<tr><td colSpan={7}>Рахунків за відбором немає.</td></tr>}</tbody></table></div></section>
      <section className="inventoryDocumentCard"><header><div><small>Довідник</small><h2>{form.id?`Каса / рахунок #${form.id}`:"Нова каса або рахунок"}</h2><p>{data.canEdit?(classificationLocked?"Тип і валюта зафіксовані. Можна змінювати назву/код, стан і основний рахунок.":"Тип і валюта стають частиною незмінної ідентичності після створення."):"Режим перегляду; змінює лише адміністратор."}</p></div></header>{notice&&<p className={notice.startsWith("⚠")?"financeError":"notice"}>{notice}</p>}
        <form className="inventoryOperations" onSubmit={save}><div><label>Назва<input required disabled={!data.canEdit} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Код<input disabled={!data.canEdit} value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Тип<select disabled={!data.canEdit||classificationLocked} value={form.accountType} onChange={e=>setForm({...form,accountType:e.target.value as AccountType})}>{Object.entries(TYPE_UK).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Валюта<input maxLength={3} disabled={!data.canEdit||classificationLocked} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label><input type="checkbox" disabled={!data.canEdit} checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Активний</label><label><input type="checkbox" disabled={!data.canEdit} checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked,active:e.target.checked?true:form.active})}/> Основний для цього типу і валюти</label>{data.canEdit&&<div><button className="primary" disabled={busy}>{form.id?"Записати":"Створити"}</button><button type="button" disabled={busy} onClick={reset}>Новий</button></div>}</div></form>
      </section></div>}
  </StaffWorkspaceShell>;
}
