export type PrintedFormRenderSnapshot={id:number;formType:string;templateVersion:number;sha256:string};
export type RenderObject=Record<string,unknown>;
export const asObject=(v:unknown):RenderObject=>v&&typeof v==="object"&&!Array.isArray(v)?v as RenderObject:{};
export const asArray=(v:unknown):unknown[]=>Array.isArray(v)?v:[];
export const escapeHtml=(v:unknown)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
export const formatDate=(v:unknown)=>{const raw=String(v??"");const d=new Date(raw);return Number.isNaN(d.getTime())?raw:new Intl.DateTimeFormat("uk-UA",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Kyiv"}).format(d);};
export const formatMoney=(v:unknown,c:unknown)=>new Intl.NumberFormat("uk-UA",{style:"currency",currency:/^[A-Z]{3}$/.test(String(c||""))?String(c):"UAH",maximumFractionDigits:0}).format(Number(v||0));
export const meta=(label:string,value:unknown)=>`<div class="item"><span>${escapeHtml(label)}</span><b>${escapeHtml(value||"—")}</b></div>`;
export const detail=(label:string,value:unknown)=>`<p><span>${escapeHtml(label)}</span><b>${escapeHtml(value||"—")}</b></p>`;
export function documentHeader(payload:RenderObject,title:string){const org=asObject(payload.organization),doc=asObject(payload.document);const states:Record<string,string>={draft:"ЧЕРНЕТКА",posted:"Проведено",reversed:"СТОРНО",cancelled:"Скасовано"};return `<header><div><small>${escapeHtml(org.name||"Організація")}</small><h1>${escapeHtml(title)}</h1><p>Документ ${escapeHtml(doc.number)}</p></div><strong>${escapeHtml(states[String(doc.state)]||doc.state)}</strong></header>`;}
export const PRINT_CSS=`@font-face{font-family:Inter;src:url(https://radiologyos.tech/fonts/inter-cyrillic.woff2) format("woff2");unicode-range:U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:Inter;src:url(https://radiologyos.tech/fonts/inter-latin.woff2) format("woff2");unicode-range:U+0000-00FF,U+2000-206F,U+20AC,U+2122,U+FEFF,U+FFFD}@page{size:A4;margin:12mm}*{box-sizing:border-box}body{margin:0;color:#142d2b;background:#fff;font:11px/1.4 Inter,Arial,sans-serif}header{display:flex;justify-content:space-between;border-bottom:2px solid #0d5b50;padding-bottom:12px;margin-bottom:15px}header small{color:#687975}h1{font-size:24px;margin:4px 0;color:#0d5b50}header p{margin:0}header strong{align-self:flex-start;border:1px solid #ccd8d4;padding:6px 9px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:7px 18px;margin-bottom:14px}.item{border-bottom:1px solid #e2e9e6;padding:4px 0}.item span{display:block;color:#6b7a76;font-size:9px}.item b{display:block}.rows p{display:grid;grid-template-columns:150px 1fr;gap:12px;border-bottom:1px solid #e6ece9;padding:6px 0;margin:0}.rows span{color:#6b7a76}.amount{display:flex;justify-content:space-between;align-items:center;background:#e8f2ef;padding:13px;margin:14px 0}.amount.refund{background:#fff0eb}.amount b{font-size:20px}table{width:100%;border-collapse:collapse;font-size:9px}th,td{border:1px solid #d8e0dd;padding:6px;text-align:left;vertical-align:top}th{background:#edf4f1}.footer{margin-top:24px;border-top:1px solid #e1e8e5;padding-top:8px;color:#778783;font-size:8px}`;
