import {PrintedFormArtifactError,type PrintedFormArtifactSnapshot,type PrintedFormPdfArtifact} from "./printed-form-artifact-types.ts";
import {printedFormState} from "./printed-form-storage-key.ts";
import type {PrintedFormObject,PrintedFormsBucket} from "./printed-form-runtime.ts";
const SHA=/^[a-f0-9]{64}$/;
export function concreteArrayBuffer(bytes:Uint8Array){const buffer=new ArrayBuffer(bytes.byteLength);new Uint8Array(buffer).set(bytes);return buffer;}
export async function sha256Bytes(bytes:Uint8Array){const digest=await crypto.subtle.digest("SHA-256",concreteArrayBuffer(bytes));const hex=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("");return {digest,hex};}
export function objectMetadata(s:PrintedFormArtifactSnapshot,binarySha256:string){return {payloadSha256:s.sha256,binarySha256,organizationId:String(s.organizationId),documentId:String(s.documentId),formType:s.formType,templateVersion:String(s.templateVersion),documentState:printedFormState(s.documentState)};}
function validate(s:PrintedFormArtifactSnapshot,o:PrintedFormObject){const md=o.customMetadata||{},expected=objectMetadata(s,md.binarySha256||"");if(o.httpMetadata?.contentType!=="application/pdf")throw new PrintedFormArtifactError("integrity_failed","Stored object is not a PDF");if(!SHA.test(md.binarySha256||""))throw new PrintedFormArtifactError("integrity_failed","Stored PDF has no valid binary hash");for(const key of ["payloadSha256","organizationId","documentId","formType","templateVersion","documentState"] as const){if(md[key]!==expected[key])throw new PrintedFormArtifactError("integrity_failed",`Stored PDF metadata mismatch: ${key}`);}return md.binarySha256;}
async function bytes(o:PrintedFormObject){if(!o.body)throw new PrintedFormArtifactError("integrity_failed","Stored PDF body is missing");return new Uint8Array(await new Response(o.body).arrayBuffer());}
export function isPdfBytes(value:Uint8Array){return value.length>=5&&new TextDecoder().decode(value.slice(0,5))==="%PDF-";}
export async function readStoredPrintedFormPdf(bucket:PrintedFormsBucket,key:string,s:PrintedFormArtifactSnapshot):Promise<PrintedFormPdfArtifact|null>{const head=await bucket.head(key);if(!head)return null;const expected=validate(s,head);const object=await bucket.get(key);if(!object)throw new PrintedFormArtifactError("integrity_failed","Stored PDF disappeared during retrieval");validate(s,object);const value=await bytes(object);const actual=await sha256Bytes(value);if(actual.hex!==expected)throw new PrintedFormArtifactError("integrity_failed","Stored PDF binary hash mismatch");if(!isPdfBytes(value))throw new PrintedFormArtifactError("integrity_failed","Stored object has an invalid PDF signature");return {key,bytes:value,binarySha256:actual.hex,etag:object.httpEtag,created:false};}
