"use client";

import { useEffect,useMemo,useState } from "react";
import StaffWorkspaceShell from "../workspace-shell";
import { roleLabelUk } from "../../../lib/labels";
import type { EquipmentRecord } from "../../../lib/equipment-registry";

type Staff={email:string;displayName:string;role:string};
type Member={email:string;displayName:string;role:string};
type Event={id:number;equipmentId:string;eventType:string;status:string;title:string;details:string;vendor:string;assignedEmail:string;dueDate:string;downtimeStart:string;downtimeEnd:string;createdAt:string};
type Payload={events:Event[];equipment:EquipmentRecord[];members:Member[];staff:Staff;canManage:boolean};
const TYPES:Record<string,string>={fault:"Несправність",repair:"Ремонт",maintenance:"ТО",inspection:"Перевірка",calibration:"Калібрування"};
const STATUSES:Record<string,string>={open:"Відкрита",in_progress:"В роботі",done:"Завершена",cancelled:"Скасована"};
const todayKyiv=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Kyiv",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());

export default function MaintenancePage(){
  const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[loaded,setLoaded]=useState(false),[creating,setCreating]=useState(false),[busy,setBusy]=useState<number|null>(null),[filter,setFilter]=useState("active");
  const [form,setForm]=useState({equipmentId:"",eventType:"fault",title:"",details:"",vendor:"",assignedEmail:"",dueDate:"",downtimeStart:""});
  async function load(){const r=await fetch("/api/staff/maintenance",{cache:"no-store"});const p=await r.json().catch(()=>({})) as Payload&{error?:string};if(!r.ok||!p.staff){setError(p.error||"Не вдалося завантажити журнал ТО");setLoaded(true);return}setData(p);setError("");setLoaded(true)}
  useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[]);
  const eq=useMemo(()=>Object.fromEntries((data?.equipment||[]).map(x=>[x.id,x])),[data]);
  const names=useMemo(()=>Object.fromEntries((data?.members||[]).map(x=>[x.email,x.displayName||x.email])),[data]);
  const today=todayKyiv(),active=(data?.events||[]).filter(x=>x.status==="open"||x.status==="in_progress"),down=active.filter(x=>x.downtimeStart&&!x.downtimeEnd),overdue=active.filter(x=>x.dueDate&&x.dueDate<today);
  const rows=(data?.events||[]).filter(x=>filter==="all"?true:filter==="active"?(x.status==="open"||x.status==="in_progress"):x.status===filter);
  async function create(){if(!form.equipmentId||!form.title.trim())return;const r=await fetch("/api/staff/maintenance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const p=await r.json().catch(()=>({})) as {error?:string};if(!r.ok){setError(p.error||"Не вдалося створити запис");return}setCreating(false);setForm({equipmentId:"",eventType:"fault",title:"",details:"",vendor:"",assignedEmail:"",dueDate:"",downtimeStart:""});await load()}
  async function patch(id:number,body:Record<string,unknown>){setBusy(id);const r=await fetch("/api/staff/maintenance",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...body})});const p=await r.json().catch(()=>({})) as {error?:string};setBusy(null);if(!r.ok){setError(p.error||"Не вдалося оновити запис");return}await load()}
  return <StaffWorkspaceShell active="equipment" title="ТО та несправності" description="Журнал обслуговування, ремонтів, калібрувань і простою діагностичного обладнання." staffName={data?.staff.displayName} staffRole={roleLabelUk(data?.staff.role)}>
    {!loaded?<p className="notice">Завантаження…</p>:<div className="maintenancePage">
      <section className="maintenanceKpis"><article><small>Активні події</small><b>{active.length}</b><span>потребують контролю</span></article><article className={down.length?"warn":""}><small>Простій</small><b>{down.length}</b><span>активних</span></article><article className={overdue.length?"warn":""}><small>Прострочено</small><b>{overdue.length}</b><span>за строком</span></article><article><small>Історія</small><b>{data?.events.length||0}</b><span>записів</span></article></section>
      <div className="maintenanceToolbar"><div>{["active","open","in_progress","done","all"].map(v=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{v==="active"?"Активні":v==="all"?"Усі":STATUSES[v]}</button>)}</div>{data?.canManage&&<button className="primary" onClick={()=>setCreating(v=>!v)}>{creating?"Закрити":"+ Додати подію"}</button>}</div>
      {creating&&<section className="maintenanceForm"><select value={form.equipmentId} onChange={e=>setForm({...form,equipmentId:e.target.value})}><option value="">Оберіть обладнання</option>{data?.equipment.map(x=><option key={x.id} value={x.id}>{[x.manufacturer,x.model].filter(Boolean).join(" ")||x.type}</option>)}</select><select value={form.eventType} onChange={e=>setForm({...form,eventType:e.target.value})}>{Object.entries(TYPES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input placeholder="Короткий опис" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Сервісна організація" value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})}/><select value={form.assignedEmail} onChange={e=>setForm({...form,assignedEmail:e.target.value})}><option value="">Без відповідального</option>{data?.members.map(x=><option key={x.email} value={x.email}>{x.displayName||x.email}</option>)}</select><label><span>Строк</span><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label><span>Початок простою</span><input type="date" value={form.downtimeStart} onChange={e=>setForm({...form,downtimeStart:e.target.value})}/></label><textarea placeholder="Деталі, код помилки, виконані роботи…" value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/><button className="primary" onClick={()=>void create()} disabled={!form.equipmentId||!form.title.trim()}>Створити запис</button></section>}
      {error&&<p className="notice error">{error}</p>}
      <section className="maintenanceList">{rows.length===0?<p className="empty">Немає записів у цьому фільтрі.</p>:rows.map(x=>{const machine=eq[x.equipmentId],isOver=(x.status==="open"||x.status==="in_progress")&&!!x.dueDate&&x.dueDate<today,isDown=!!x.downtimeStart&&!x.downtimeEnd&&(x.status==="open"||x.status==="in_progress");return <article key={x.id} className={`maintenanceCard ${x.status}${isOver?" overdue":""}`}><header><div><span className={`eventType ${x.eventType}`}>{TYPES[x.eventType]||x.eventType}</span><b>{x.title}</b><small>{machine?[machine.manufacturer,machine.model].filter(Boolean).join(" ")||machine.type:x.equipmentId}</small></div><em>{STATUSES[x.status]||x.status}</em></header><div className="maintenanceMeta">{x.assignedEmail&&<span>Відповідальний: <b>{names[x.assignedEmail]||x.assignedEmail}</b></span>}{x.vendor&&<span>Сервіс: <b>{x.vendor}</b></span>}{x.dueDate&&<span className={isOver?"danger":""}>Строк: <b>{x.dueDate}</b></span>}{isDown&&<span className="danger">Простій з <b>{x.downtimeStart}</b></span>}</div>{x.details&&<p>{x.details}</p>}{data?.canManage&&x.status!=="done"&&x.status!=="cancelled"&&<footer><button disabled={busy===x.id} onClick={()=>void patch(x.id,{status:"in_progress"})}>В роботу</button>{isDown&&<button disabled={busy===x.id} onClick={()=>void patch(x.id,{downtimeEnd:today})}>Завершити простій</button>}<button className="primary" disabled={busy===x.id} onClick={()=>void patch(x.id,{status:"done",downtimeEnd:isDown?today:x.downtimeEnd})}>Завершити</button><button disabled={busy===x.id} onClick={()=>void patch(x.id,{status:"cancelled"})}>Скасувати</button></footer>}</article>})}</section>
    </div>}
  </StaffWorkspaceShell>;
}
