"use client";

import { useEffect,useMemo,useState } from "react";
import StaffWorkspaceShell from "../workspace-shell";
import { roleLabelUk } from "../../../lib/labels";
import type { EquipmentRecord } from "../../../lib/equipment-registry";

type Staff={email:string;displayName:string;role:string};
type Member={email:string;displayName:string;role:string};
type Event={id:number;equipmentId:string;eventType:string;status:string;title:string;details:string;vendor:string;assignedEmail:string;dueDate:string;downtimeStart:string;downtimeEnd:string;createdBy:string;completedBy:string;completedAt:string;createdAt:string;updatedAt:string};
type Payload={events:Event[];equipment:EquipmentRecord[];members:Member[];staff:Staff;canManage:boolean};

const TYPE_LABEL:Record<string,string>={fault:"Несправність",repair:"Ремонт",maintenance:"ТО",inspection:"Перевірка",calibration:"Калібрування"};
const STATUS_LABEL:Record<string,string>={open:"Відкрита",in_progress:"В роботі",done:"Завершена",cancelled:"Скасована"};
function todayKyiv(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Kyiv",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}

export default function MaintenancePage(){
  const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[loaded,setLoaded]=useState(false),[creating,setCreating]=useState(false),[busy,setBusy]=useState<number|null>(null),[filter,setFilter]=useState("open");
  const [form,setForm]=useState({equipmentId:"",eventType:"fault",title:"",details:"",vendor:"",assignedEmail:"",dueDate:"",downtimeStart:""});
  async function load(){const res=await fetch("/api/staff/maintenance",{cache:"no-store"});const p=await res.json().catch(()=>({})) as Payload&{error?:string};if(!res.ok||!p.staff){setError(p.error||"Не вдалося завантажити журнал ТО");setLoaded(true);return;}setData(p);setLoaded(true);setError("");}
  useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[]);
  const equipmentById=useMemo(()=>Object.fromEntries((data?.equipment||[]).map(e=>[e.id,e])),[data]);
  const nameByEmail=useMemo(()=>Object.fromEntries((data?.members||[]).map(m=>[m.email,m.displayName||m.email])),[data]);
  const today=todayKyiv();
  const visible=useMemo(()=>{const rows=data?.events||[];if(filter==="all")return rows;if(filter==="active")return rows.filter(e=>e.status==="open"||e.status==="in_progress");return rows.filter(e=>e.status===filter)},[data,filter]);
  const activeCount=(data?.events||[]).filter(e=>e.status==="open"||e.status==="in_progress").length;
  const downtimeCount=(data?.events||[]).filter(e=>(e.status==="open"||e.status==="in_progress")&&e.downtimeStart&&!e.downtimeEnd).length;
  const overdueCount=(data?.events||[]).filter(e=>(e.status==="open"||e.status==="in_progress")&&e.dueDate&&e.dueDate<today).length;
  async function create(){if(!form.equipmentId||!form.title.trim())return;const res=await fetch("/api/staff/maintenance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const p=await res.json().catch(()=>({})) as {error?:string};if(!res.ok){setError(p.error||"Не вдалося створити запис");return;}setCreating(false);setForm({equipmentId:"",eventType:"fault",title:"",details:"",vendor:"",assignedEmail:"",dueDate:"",downtimeStart:""});await load();}
  async function patch(id:number,body:Record<string,unknown>){setBusy(id);const res=await fetch("/api/staff/maintenance",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...body})});const p=await res.json().catch(()=>({})) as {error?:string};setBusy(null);if(!res.ok){setError(p.error||"Не вдалося оновити запис");return;}await load();}
  return <StaffWorkspaceShell active="maintenance" title="ТО та несправності" description="Журнал обслуговування, ремонтів, калібрувань і простою діагностичного обладнання." staffName={data?.staff.displayName} staffRole={roleLabelUk(data?.staff.role)}>
    {!loaded?<p className="notice">Завантаження…</p>:<div className="maintenancePage">
      <section className="maintenanceKpis"><article><small>Активні події</small><b>{activeCount}</b><span>потребують контролю</span></article><article className={downtimeCount?"warn":""}><small>Простій</small><b>{downtimeCount}</b><span>апаратів/подій</span></article><article className={overdueCount?"warn":""}><small>Прострочено</small><b>{overdueCount}</b><span>за строком</span></article><article><small>Всього записів</small><b>{data?.events.length||0}</b><span>історія сервісу</span></article></section>
      <div className="maintenanceToolbar"><div>{["active","open","in_progress","done","all"].map(v=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{v==="active"?"Активні":v==="all"?"Усі":STATUS_LABEL[v]}</button>)}</div>{data?.canManage&&<button className="primary" onClick={()=>setCreating(v=>!v)}>{creating?"Закрити":"+ Додати подію"}</button>}</div>
      {creating&&<section className="maintenanceForm"><select value={form.equipmentId} onChange={e=>setForm({...form,equipmentId:e.target.value})}><option value="">Оберіть обладнання</option>{data?.equipment.map(e=><option key={e.id} value={e.id}>{[e.manufacturer,e.model].filter(Boolean).join(" ")||e.type}</option>)}</select><select value={form.eventType} onChange={e=>setForm({...form,eventType:e.target.value})}>{Object.entries(TYPE_LABEL).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input placeholder="Короткий опис" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Сервісна організація" value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})}/><select value={form.assignedEmail} onChange={e=>setForm({...form,assignedEmail:e.target.value})}><option value="">Без відповідального</option>{data?.members.map(m=><option key={m.email} value={m.email}>{m.displayName||m.email}</option>)}</select><label><span>Строк</span><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label><span>Початок простою</span><input type="date" value={form.downtimeStart} onChange={e=>setForm({...form,downtimeStart:e.target.value})}/></label><textarea placeholder="Деталі, код помилки, виконані роботи…" value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/><button className="primary" onClick={()=>void create()} disabled={!form.equipmentId||!form.title.trim()}>Створити запис</button></section>}
      {error&&<p className="notice error">{error}</p>}
      <section className="maintenanceList">{visible.length===0?<p className="empty">Немає записів у цьому фільтрі.</p>:visible.map(ev=>{const eq=equipmentById[ev.equipmentId];const overdue=(ev.status==="open"||ev.status==="in_progress")&&!!ev.dueDate&&ev.dueDate<today;const down=!!ev.downtimeStart&&!ev.downtimeEnd&&(ev.status==="open"||ev.status==="in_progress");return <article key={ev.id} className={`maintenanceCard ${ev.status}${overdue?" overdue":""}`}><header><div><span className={`eventType ${ev.eventType}`}>{TYPE_LABEL[ev.eventType]||ev.eventType}</span><b>{ev.title}</b><small>{eq?[eq.manufacturer,eq.model].filter(Boolean).join(" ")||eq.type:ev.equipmentId}</small></div><em>{STATUS_LABEL[ev.status]||ev.status}</em></header><div className="maintenanceMeta">{ev.assignedEmail&&<span>Відповідальний: <b>{nameByEmail[ev.assignedEmail]||ev.assignedEmail}</b></span>}{ev.vendor&&<span>Сервіс: <b>{ev.vendor}</b></span>}{ev.dueDate&&<span className={overdue?"danger":""}>Строк: <b>{ev.dueDate}</b></span>}{down&&<span className="danger">Простій з <b>{ev.downtimeStart}</b></span>}</div>{ev.details&&<p>{ev.details}</p>}{data?.canManage&&ev.status!=="done"&&ev.status!=="cancelled"&&<footer><button disabled={busy===ev.id} onClick={()=>void patch(ev.id,{status:"in_progress"})}>В роботу</button>{down&&<button disabled={busy===ev.id} onClick={()=>void patch(ev.id,{downtimeEnd:today})}>Завершити простій</button>}<button className="primary" disabled={busy===ev.id} onClick={()=>void patch(ev.id,{status:"done",downtimeEnd:down?today:ev.downtimeEnd})}>Завершити</button><button disabled={busy===ev.id} onClick={()=>void patch(ev.id,{status:"cancelled"})}>Скасувати</button></footer>}</article>})}</section>
    </div>}
  </StaffWorkspaceShell>;
}
