"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import StaffWorkspaceShell from "../workspace-shell";

type Staff={email:string;displayName:string;role:string};
type DraftPurchase={documentId:number;number:string;occurredAt:string;comment:string;lineId:number;lineNo:number;itemId:number;itemName:string;unit:string;quantity:number;supplierId:number;supplierName:string;unitCost:number;lineAmount:number;warehouseName:string;lotNumber:string};
type Payable={supplierId:number;supplierName:string;receiptDocumentId:number;currency:string;balance:number;receiptNumber:string;receiptOccurredAt:string};
type Payment={id:number;number:string;supplierId:number;supplierName:string;cashAccountId:number;cashAccountName:string;currency:string;amount:number;occurredAt:string;state:string;comment:string;allocationCount:number;postedBy:string;postedAt:string};
type CashBalance={cashAccountId:number;code:string;name:string;accountType:string;currency:string;balance:number;active:number;isDefault:number};
type Payload={draftPurchases:DraftPurchase[];payables:Payable[];payments:Payment[];cashBalances:CashBalance[];staff:Staff;canManage:boolean;error?:string};
type Tab="valuation"|"payables"|"payments"|"cash";

const STATE_UK:Record<string,string>={draft:"Чернетка",posted:"Проведено",cancelled:"Скасовано"};
function money(value:number,currency="UAH"){return new Intl.NumberFormat("uk-UA",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value||0));}
function dateTime(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString("uk-UA",{dateStyle:"medium",timeStyle:"short"});}

export default function SupplierPayablesPage(){
  const [data,setData]=useState<Payload|null>(null);const [error,setError]=useState("");const [toast,setToast]=useState("");const [busy,setBusy]=useState(false);const [tab,setTab]=useState<Tab>("valuation");
  const [costs,setCosts]=useState<Record<number,string>>({});
  const [paymentForm,setPaymentForm]=useState({supplierId:"",receiptDocumentId:"",amount:"",cashAccountId:"",comment:""});

  const load=useCallback(async()=>{try{const response=await fetch("/api/staff/supplier-payables",{cache:"no-store"});const payload=await response.json().catch(()=>({})) as Payload;if(!response.ok)throw new Error(payload.error||"Не вдалося завантажити закупівлі");setData(payload);setCosts(current=>{const next={...current};for(const row of payload.draftPurchases||[])if(next[row.lineId]===undefined)next[row.lineId]=row.unitCost?String(row.unitCost):"";return next;});setError("");}catch(e){setError(e instanceof Error?e.message:"Не вдалося завантажити закупівлі");}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);

  const totalDebt=useMemo(()=>data?.payables.reduce((sum,row)=>sum+Number(row.balance||0),0)||0,[data]);
  const draftDocuments=useMemo(()=>new Set((data?.draftPurchases||[]).map(row=>row.documentId)).size,[data]);
  const activeAccounts=useMemo(()=>data?.cashBalances.filter(row=>row.active)||[],[data]);

  async function action(body:Record<string,unknown>,ok:string){setBusy(true);setToast("");try{const response=await fetch("/api/staff/supplier-payables",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({})) as {error?:string;document?:{id:number}};if(!response.ok){setToast(`⚠ ${payload.error||"Помилка операції"}`);return null;}setToast(`✓ ${ok}`);await load();return payload;}finally{setBusy(false);}}
  async function saveCost(row:DraftPurchase){const unitCost=Number(costs[row.lineId]);if(!Number.isInteger(unitCost)||unitCost<=0){setToast("⚠ Закупівельна ціна має бути цілим числом гривень і більшою за нуль");return;}await action({action:"value_receipt",documentId:row.documentId,lines:[{lineId:row.lineId,unitCost}]},`Оцінку ${row.number} збережено`);}
  function startPayment(row:Payable){setPaymentForm({supplierId:String(row.supplierId),receiptDocumentId:String(row.receiptDocumentId),amount:String(row.balance),cashAccountId:String(activeAccounts.find(account=>account.isDefault)?.cashAccountId||activeAccounts[0]?.cashAccountId||""),comment:`Оплата за надходження ${row.receiptNumber}`});setTab("payables");window.setTimeout(()=>document.getElementById("supplier-payment-form")?.scrollIntoView({behavior:"smooth",block:"center"}),0);}
  async function createPayment(e:React.FormEvent){e.preventDefault();const created=await action({action:"create_payment",supplierId:Number(paymentForm.supplierId),cashAccountId:Number(paymentForm.cashAccountId),allocations:[{receiptDocumentId:Number(paymentForm.receiptDocumentId),amount:Number(paymentForm.amount)}],comment:paymentForm.comment},"Чернетку оплати створено");if(created){setPaymentForm({supplierId:"",receiptDocumentId:"",amount:"",cashAccountId:"",comment:""});setTab("payments");}}

  return <StaffWorkspaceShell active="purchases" title="Кредиторка постачальників" description="Закупівельна вартість надходжень, борги постачальникам, оплати та залишки по касах/рахунках." staffName={data?.staff.displayName||data?.staff.email} staffRole={data?.staff.role}>
    {toast&&<p className={`inventoryToast${toast.startsWith("⚠")?" warn":""}`} role="status" onClick={()=>setToast("")}>{toast}</p>}
    <section className="financeSummary" aria-label="Підсумок закупівель"><article><span>Відкритий борг</span><b>{money(totalDebt)}</b><small>проведені надходження</small></article><article><span>До оцінки</span><b>{draftDocuments}</b><small>чернеток надходжень</small></article><article><span>Оплат</span><b>{data?.payments.length||0}</b><small>журнал документів</small></article><article><span>Рахунків / кас</span><b>{activeAccounts.length}</b><small>активні UAH</small></article></section>
    <section className="financeJournal"><header className="financeToolbar"><div className="financeTabs" role="tablist"><button type="button" className={tab==="valuation"?"active":""} onClick={()=>setTab("valuation")}>Оцінка надходжень</button><button type="button" className={tab==="payables"?"active":""} onClick={()=>setTab("payables")}>Кредиторка</button><button type="button" className={tab==="payments"?"active":""} onClick={()=>setTab("payments")}>Оплати</button><button type="button" className={tab==="cash"?"active":""} onClick={()=>setTab("cash")}>Каси / рахунки</button><button type="button" onClick={()=>window.location.assign("/staff/inventory")}>Склад ↗</button><button type="button" onClick={()=>window.location.assign("/staff/counterparties")}>Постачальники ↗</button></div><button type="button" disabled={busy} onClick={()=>void load()}>Оновити</button></header>
      {error&&<p className="financeError">{error}</p>}{!data&&!error&&<p className="financeLoading">Завантаження закупівель…</p>}

      {data&&tab==="valuation"&&<div className="financeTableWrap"><table className="financeTable"><thead><tr><th>Надходження</th><th>Матеріал</th><th>Постачальник</th><th>Склад / партія</th><th className="num">Кількість</th><th className="num">Ціна, грн</th><th className="num">Сума</th><th/></tr></thead><tbody>{data.draftPurchases.map(row=><tr key={row.lineId}><td><b>{row.number}</b><small>{dateTime(row.occurredAt)}</small></td><td><b>{row.itemName}</b><small>рядок {row.lineNo}</small></td><td>{row.supplierName}</td><td>{row.warehouseName}<small>{row.lotNumber||"без № партії"}</small></td><td className="num">{row.quantity} {row.unit}</td><td className="num"><input style={{width:"110px"}} type="number" min="1" step="1" value={costs[row.lineId]??""} onChange={e=>setCosts({...costs,[row.lineId]:e.target.value})}/></td><td className="num">{money(Number(row.quantity)*Number(costs[row.lineId]||0))}</td><td><button type="button" disabled={busy} onClick={()=>void saveCost(row)}>Зберегти</button></td></tr>)}</tbody></table>{data.draftPurchases.length===0&&<p className="financeEmpty">Чернеток надходжень від постачальників, що очікують оцінки, немає.</p>}</div>}

      {data&&tab==="payables"&&<><div className="financeTableWrap"><table className="financeTable"><thead><tr><th>Постачальник</th><th>Надходження</th><th>Дата</th><th className="num">Борг</th><th/></tr></thead><tbody>{data.payables.map(row=><tr key={`${row.supplierId}-${row.receiptDocumentId}`}><td><b>{row.supplierName}</b></td><td>{row.receiptNumber}</td><td>{dateTime(row.receiptOccurredAt)}</td><td className="num negative">{money(row.balance,row.currency)}</td><td><button type="button" onClick={()=>startPayment(row)}>Оплатити</button></td></tr>)}</tbody></table>{data.payables.length===0&&<p className="financeEmpty">Відкритої кредиторської заборгованості немає.</p>}</div>
        <form id="supplier-payment-form" className="inventoryOperations" onSubmit={createPayment}><section><h3>Нова оплата постачальнику</h3><p className="inventoryFormHint">Створюється чернетка. Рух грошей і погашення боргу виникнуть лише після «Провести».</p><select required value={paymentForm.cashAccountId} onChange={e=>setPaymentForm({...paymentForm,cashAccountId:e.target.value})}><option value="">Оберіть рахунок / касу</option>{activeAccounts.map(row=><option key={row.cashAccountId} value={row.cashAccountId}>{row.name}{row.code?` · ${row.code}`:""} · баланс {money(row.balance,row.currency)}</option>)}</select><input required type="number" min="1" step="1" placeholder="Сума, грн" value={paymentForm.amount} onChange={e=>setPaymentForm({...paymentForm,amount:e.target.value})}/><input placeholder="Примітка" value={paymentForm.comment} onChange={e=>setPaymentForm({...paymentForm,comment:e.target.value})}/><button disabled={busy||!paymentForm.receiptDocumentId}>Створити чернетку</button></section></form></>}

      {data&&tab==="payments"&&<div className="financeTableWrap"><table className="financeTable"><thead><tr><th>Документ</th><th>Дата</th><th>Постачальник</th><th>Каса / рахунок</th><th className="num">Сума</th><th>Стан</th><th/></tr></thead><tbody>{data.payments.map(row=><tr key={row.id}><td><b>{row.number}</b><small>{row.allocationCount} надходж.</small></td><td>{dateTime(row.occurredAt)}</td><td>{row.supplierName}</td><td>{row.cashAccountName}</td><td className="num negative">−{money(row.amount,row.currency)}</td><td><span className={`financeState state-${row.state}`}>{STATE_UK[row.state]||row.state}</span></td><td>{row.state==="draft"&&<><button type="button" disabled={busy} onClick={()=>void action({action:"post_payment",documentId:row.id},`${row.number} проведено`)}>Провести</button> <button type="button" disabled={busy} onClick={()=>void action({action:"cancel_payment",documentId:row.id},`${row.number} скасовано`)}>Скасувати</button></>}</td></tr>)}</tbody></table>{data.payments.length===0&&<p className="financeEmpty">Оплат постачальникам ще немає.</p>}</div>}

      {data&&tab==="cash"&&<div className="financeTableWrap"><table className="financeTable"><thead><tr><th>Рахунок / каса</th><th>Тип</th><th>Код</th><th>Валюта</th><th className="num">Баланс</th><th>Стан</th></tr></thead><tbody>{data.cashBalances.map(row=><tr key={row.cashAccountId}><td><b>{row.name}</b>{row.isDefault?<small>за замовчуванням</small>:null}</td><td>{row.accountType}</td><td>{row.code||"—"}</td><td>{row.currency}</td><td className="num">{money(row.balance,row.currency)}</td><td>{row.active?"Активний":"Неактивний"}</td></tr>)}</tbody></table></div>}
    </section>
  </StaffWorkspaceShell>;
}
