// Private iCal feed of appointments for a Google Calendar subscription.
// Access is gated by the calendar_token query parameter (set/regenerated by an
// admin in /staff/settings). Contains patient data, so the token is the secret.

import { getSetting } from "../../../lib/settings";
import { buildIcs, type CalendarBooking } from "../../../lib/calendar-ics";

function dbBinding() {
  return (globalThis as typeof globalThis & { __RADIOLOGY_DB__?: D1Database }).__RADIOLOGY_DB__;
}

export async function GET(request: Request) {
  const db = dbBinding();
  if (!db) return new Response("Service unavailable", { status: 503 });

  const token = new URL(request.url).searchParams.get("token") || "";
  const expected = await getSetting(db, "calendar_token");
  if (!expected || token !== expected) {
    return new Response("Not found", { status: 404 });
  }

  const rows = await db.prepare(
    `SELECT code, service, name, desired_date AS desiredDate, desired_time AS desiredTime,
       duration_minutes AS durationMinutes, status, phone, patient_category AS category
     FROM bookings
     WHERE status IN ('new','confirmed','rescheduled')
       AND desired_date >= date('now','-1 day')
     ORDER BY desired_date, desired_time
     LIMIT 1000`
  ).all<CalendarBooking>();

  const ics = buildIcs(rows.results || []);
  return new Response(ics, {
    status: 200,
    headers: {
      "content-type": "text/calendar; charset=utf-8",
      "content-disposition": 'inline; filename="radiologyos.ics"',
      "cache-control": "no-store",
    },
  });
}
